version: '2'
services:
  datastore:
    container_name: kintai_datastore
    image: busybox
    volumes:
      - /share
      - ./mysql/volumes:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  server:
    container_name: kintai_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - ${SERVER_PORT}:80
    volumes_from:
      - datastore
    depends_on:
      - datastore
  app:
    container_name: kintai_rails
    build:
      context: .
      dockerfile: ./rails/Dockerfile
    command: bundle exec puma -C config/puma.rb -e ${RAILS_ENVIRONMENT}
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APPLICATION_PATH}:/app
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - datastore
    depends_on:
      - db
    links:
      - db
      - db:database
      - db:mysql
    extends:
      file: ./mysql/password.yml
      service: password
  db:
    container_name: kintai_mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    volumes_from:
      - datastore
    depends_on:
      - datastore
    extends:
      file: ./mysql/password.yml
      service: password
